version: '2'
services:
    healthpoints-app:
        image: healthpoints
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://healthpoints-mysql:3306/healthpoints?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://healthpoints-elasticsearch:9200
        ports:
            - 8080:8080
    healthpoints-mysql:
        extends:
            file: mysql.yml
            service: healthpoints-mysql
    healthpoints-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: healthpoints-elasticsearch
